/* Atril Drive: append-only recovery snapshots. Tokens stay in memory. */
(()=>{'use strict';
const CLIENT_ID='603129121212-q6bdegpvpm7cj24nhvfi26q1vdp5gsv8.apps.googleusercontent.com';
const SCOPE='https://www.googleapis.com/auth/drive.file';
let token='',expires=0,account='',folder='',busy=false,timer=null,client=null,lastSaved='',base=null,seen=new Set();
const deviceKey='atril.device.v1';
let device;try{device=localStorage.getItem(deviceKey);if(!device){device=crypto.randomUUID();localStorage.setItem(deviceKey,device);}}catch{device=crypto.randomUUID();}
const panel=document.createElement('section');panel.className='drive-panel';panel.innerHTML='<h2>Tu escritura, también en Drive</h2><p>Opcional. Guarda borrador, nota activa y colección en tu carpeta Atril. El modo local sigue disponible.</p><div class="toolbar"><button id="drive-connect">Conectar con Google</button><button id="drive-sync" disabled>Guardar y recuperar de Drive</button><button id="drive-disconnect" hidden>Desconectar</button><a id="drive-folder" hidden target="_blank" rel="noopener">Abrir carpeta Atril ↗</a><label class="file-button">Añadir nota .txt<input id="drive-import" type="file" accept=".txt,text/plain"></label><button id="drive-backup">Copia completa .json</button><label class="file-button">Recuperar copia .json<input id="drive-restore" type="file" accept=".json,application/json"></label></div><p id="drive-status" role="status" aria-live="polite">Modo local. Todavía no hay copia en Drive.</p><details><summary>Privacidad y recuperación</summary><p><a href="privacy.html" target="_blank" rel="noopener">Política de privacidad</a></p><p>Google recibe los textos al conectar. Atril solo accede a archivos que crea; no lee el resto de tu Drive. No usa un servidor intermediario ni guarda tu contraseña. La autorización caduca: si hace falta, pulsa Conectar de nuevo. Sin conexión, escribe en este navegador y reconecta para guardar. No es una garantía contra borrar los datos del navegador antes de sincronizar.</p><p>Se conservan versiones de recuperación JSON y copias .txt, sin borrar versiones anteriores. Puedes descargarlas desde Drive; consumen espacio de tu cuenta. Los cambios simultáneos se conservan como notas de recuperación. Para añadir un texto, usa Añadir nota .txt aquí: los archivos añadidos directamente en Drive no se leen automáticamente con este permiso.</p><p>Al desconectar se mantiene la copia local. En un dispositivo compartido descarga tus copias y borra los datos del sitio manualmente. No mezcles cuentas: Atril pedirá confirmar antes de copiar la escritura local a una cuenta distinta.</p></details>';
document.querySelector('.intro').after(panel);
const el=id=>document.getElementById(id),status=t=>el('drive-status').textContent=t;
const uid=()=>crypto.randomUUID();
const copy=x=>JSON.parse(JSON.stringify(x));
function snapshot(){return {schema:1,device,at:new Date().toISOString(),draft:{title:el('title').value,text:el('editor').value},notebook:copy({...notebook,active:activeFromFields()})};}
function fingerprint(s){return JSON.stringify({draft:s.draft,notebook:s.notebook});}
function valid(s){return !!(s&&s.schema===1&&s.draft&&typeof s.draft.title==='string'&&typeof s.draft.text==='string'&&s.notebook&&s.notebook.active&&typeof s.notebook.active.title==='string'&&typeof s.notebook.active.text==='string'&&Array.isArray(s.notebook.notes)&&s.notebook.notes.length<=10000&&s.notebook.notes.every(n=>typeof n.id==='string'&&typeof n.title==='string'&&typeof n.text==='string'));}
function changed(a,b){return JSON.stringify(a)!==JSON.stringify(b);}
function nonempty(a){return a&&(a.title.trim()||a.text.trim());}
function merge(local,remote,ancestor){const result=copy(local),notes=result.notebook.notes;let recovered=0;
const preserve=(n,label)=>{if(!nonempty(n))return;const title=(n.title||'Sin título')+' · recuperación '+label;if(notes.some(x=>x.title===title&&x.text===n.text))return;notes.unshift({id:'recovery-'+uid(),title,text:n.text,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});recovered++;};
for(const rn of remote.notebook.notes){const ln=notes.find(n=>n.id===rn.id),old=ancestor?.notebook.notes.find(n=>n.id===rn.id);if(!ln){if(!old||changed(rn,old))notes.push(copy(rn));continue;}if(ln.title===rn.title&&ln.text===rn.text)continue;if(old&&!changed(ln,old)){Object.assign(ln,rn);}else if(!old||changed(rn,old)){preserve(rn,'Drive');}}
// A remote deletion only propagates if the local note is unchanged from the ancestor.
if(ancestor)notes.splice(0,notes.length,...notes.filter(n=>!ancestor.notebook.notes.some(o=>o.id===n.id&&!changed(o,n))||remote.notebook.notes.some(r=>r.id===n.id)));
for(const [key,get,set] of [['borrador',s=>s.draft,(s,v)=>s.draft=v],['nota activa',s=>s.notebook.active,(s,v)=>s.notebook.active=v]]){const l=get(local),r=get(remote),a=ancestor&&get(ancestor);if(!changed(l,r))continue;if(a&&!changed(l,a))set(result,copy(r));else if(!a&&!nonempty(l))set(result,copy(r));else if(!a||changed(r,a))preserve(r,key+' de Drive');}
return {state:result,recovered};}
function install(s){if(!valid(s)||!notebookReadable)throw Error('No se pueden recuperar los datos sin sobrescribir datos ilegibles. Descarga una copia.');
// Backup before replacing fields, and check storage before changing the visible editor.
localStorage.setItem('atril.before-drive.v1',JSON.stringify(snapshot()));
localStorage.setItem('atril.draft.v1',JSON.stringify(s.draft));
if(!persistNotebook(s.notebook))throw Error('No se pudo guardar la colección local. Descarga una copia.');
el('title').value=s.draft.title;el('editor').value=s.draft.text;metrics();fillActive();renderNotes();}
async function api(path,options={}){if(!token||Date.now()>expires)throw Error('La sesión ha caducado. Pulsa Conectar con Google; tu escritura sigue local.');const res=await fetch('https://www.googleapis.com/'+path,{...options,headers:{...options.headers,Authorization:'Bearer '+token}});if(!res.ok){if(res.status===401){token='';throw Error('La sesión ha caducado. Conecta de nuevo.');}throw Error('Drive respondió '+res.status+'. Tu escritura sigue guardada localmente; vuelve a intentarlo.');}return res;}
async function json(path,options){return (await api(path,options)).json();}
async function list(q){let files=[],page='';do{const p=new URLSearchParams({q,fields:'nextPageToken,files(id,name,appProperties,modifiedTime,webViewLink)',pageSize:'1000'});if(page)p.set('pageToken',page);const r=await json('drive/v3/files?'+p);files.push(...r.files);page=r.nextPageToken||'';}while(page);return files;}
async function getFolder(){const fs=await list("trashed=false and mimeType='application/vnd.google-apps.folder' and appProperties has {key='atrilFolder' and value='v1'}");if(fs.length)return fs[0];return json('drive/v3/files?fields=id,webViewLink',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Atril',mimeType:'application/vnd.google-apps.folder',appProperties:{atrilFolder:'v1'}})});}
async function createFile(name,text,mime,props){const boundary='atril_'+uid(),metadata={name,mimeType:mime,parents:[folder],appProperties:props};const body='--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify(metadata)+'\r\n--'+boundary+'\r\nContent-Type: '+mime+'\r\n\r\n'+text+'\r\n--'+boundary+'--';return json('upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink',{method:'POST',headers:{'Content-Type':'multipart/related; boundary='+boundary},body});}
async function remoteStates(){const fs=await list("'"+folder+"' in parents and trashed=false and appProperties has {key='atrilKind' and value='snapshot'}");const latest=new Map();for(const f of fs){const d=f.appProperties?.device||f.id;const old=latest.get(d);if(!old||f.name>old.name)latest.set(d,f);}const states=[];for(const f of latest.values()){const r=await api('drive/v3/files/'+encodeURIComponent(f.id)+'?alt=media');const text=await r.text();if(text.length>20000000)throw Error('Una copia de Drive supera 20 MB. No se ha reemplazado nada.');let s;try{s=JSON.parse(text);}catch{throw Error('Una copia de Drive no se puede leer. No se ha reemplazado nada.');}if(!valid(s))throw Error('Formato de copia de Drive no válido. No se ha reemplazado nada.');states.push(s);}return states.sort((a,b)=>b.at.localeCompare(a.at));}
async function sync(){if(busy||!token)return;busy=true;el('drive-sync').disabled=true;status('Guardando y recuperando de Drive…');try{const local=snapshot();let combined=local,recovered=0;const rs=await remoteStates();for(const r of rs){if(seen.has(fingerprint(r))||(base&&fingerprint(r)===fingerprint(base)))continue;const m=merge(combined,r,base);combined=m.state;recovered+=m.recovered;}
// Preserve typing performed during network reads by merging again, never replacing it blindly.
const current=snapshot();if(fingerprint(current)!==fingerprint(local)){const m=merge(current,combined,local);combined=m.state;recovered+=m.recovered;}
if(fingerprint(combined)!==fingerprint(current))install(combined);
const state=snapshot(),fp=fingerprint(state);if(fp!==lastSaved){const stamp=new Date().toISOString().replace(/[:.]/g,'-');await createFile('atril-recuperacion-'+stamp+'-'+device.slice(0,8)+'.json',JSON.stringify(state,null,2),'application/json',{atrilKind:'snapshot',device});
// Snapshots are authoritative; plain text copies are convenient exports, never overwritten.
const previous=base;for(const [kind,n,old] of [['borrador',state.draft,previous?.draft],['nota-activa',state.notebook.active,previous?.notebook.active]]){if(nonempty(n)&&(!old||old.title!==n.title||old.text!==n.text))await createFile('atril-'+kind+'-'+stamp+'.txt',noteText(n),'text/plain',{atrilKind:kind,device});}for(const n of state.notebook.notes){const old=previous?.notebook.notes.find(x=>x.id===n.id);if(!old||old.title!==n.title||old.text!==n.text)await createFile(noteFilename(n).replace(/\.txt$/,'')+'-'+stamp+'.txt',noteText(n),'text/plain',{atrilKind:'note',noteId:n.id});}
lastSaved=fp;}
for(const r of rs)seen.add(fingerprint(r));seen.add(fp);localStorage.setItem('atril.drive-seen.'+account,JSON.stringify([...seen].slice(-100)));base=copy(state);localStorage.setItem('atril.drive-base.'+account,JSON.stringify(base));status((recovered?'Conservadas '+recovered+' copias de recuperación. ':'')+'Copia en Drive confirmada a las '+new Date().toLocaleTimeString('es-ES')+'.');if(fingerprint(snapshot())!==fp)schedule();
}catch(e){status(e.message||'No se pudo guardar en Drive. Tu copia local sigue disponible.');}finally{busy=false;el('drive-sync').disabled=!token;}}
function schedule(){if(!token)return;status('Guardado local. Pendiente de copiar a Drive…');clearTimeout(timer);timer=setTimeout(sync,15000);}
async function connected(response){if(response.error){status('No se completó la conexión. El modo local sigue disponible.');return;}if(!google.accounts.oauth2.hasGrantedAllScopes(response,SCOPE)){status('Falta el permiso de archivos de Atril. No se ha subido nada.');return;}token=response.access_token;expires=Date.now()+response.expires_in*1000-30000;try{const who=await json('drive/v3/about?fields=user(permissionId,emailAddress)');account=who.user.permissionId;const previous=localStorage.getItem('atril.drive-account');if(previous!==account&&nonempty({title:snapshot().draft.title,text:snapshot().draft.text+snapshot().notebook.active.text+snapshot().notebook.notes.map(n=>n.text).join('')})){if(!confirm('¿Copiar la escritura local de este navegador a '+who.user.emailAddress+'? Se conservarán también las notas que ya haya en Drive. Cancelar deja el modo local.')){disconnect();return;}}
localStorage.setItem('atril.drive-account',account);try{base=JSON.parse(localStorage.getItem('atril.drive-base.'+account)||'null');if(base&&!valid(base))base=null;}catch{base=null;}
try{seen=new Set(JSON.parse(localStorage.getItem('atril.drive-seen.'+account)||'[]'));}catch{seen=new Set();}const f=await getFolder();folder=f.id;el('drive-folder').href=f.webViewLink||('https://drive.google.com/drive/folders/'+encodeURIComponent(folder));el('drive-folder').hidden=false;el('drive-disconnect').hidden=false;el('drive-sync').disabled=false;el('drive-connect').textContent='Reconectar con Google';status('Conectado a '+who.user.emailAddress+'.');await sync();}catch(e){status(e.message);}}
function disconnect(){clearTimeout(timer);token='';expires=0;folder='';account='';base=null;seen=new Set();lastSaved='';el('drive-sync').disabled=true;el('drive-disconnect').hidden=true;el('drive-folder').hidden=true;el('drive-connect').textContent='Conectar con Google';status('Desconectado. Las copias locales y las de Drive no se han borrado.');}
el('drive-connect').onclick=()=>{if(!client){if(!window.google?.accounts?.oauth2){status('No se ha cargado Google. Comprueba la conexión y vuelve a intentarlo.');return;}client=google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:SCOPE,include_granted_scopes:false,callback:connected,error_callback:()=>status('Conexión cancelada o ventana bloqueada. El modo local sigue disponible.')});}client.requestAccessToken({prompt:'select_account'});};
el('drive-sync').onclick=sync;el('drive-disconnect').onclick=()=>{if(busy){status('Espera a que termine la copia antes de desconectar.');return;}disconnect();};
el('drive-backup').onclick=()=>downloadPlain(JSON.stringify(snapshot(),null,2),'atril-copia-completa.json');
el('drive-restore').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>20000000)throw Error('La copia supera 20 MB.');const restored=JSON.parse(await f.text());if(!valid(restored))throw Error('No es una copia completa válida de Atril.');const m=merge(snapshot(),restored,null);install(m.state);schedule();status('Copia recuperada sin borrar la escritura actual.'+(m.recovered?' Se han conservado notas de recuperación.':''));}catch(err){status(err.message);}e.target.value='';};
el('drive-import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2000000)throw Error('El archivo supera 2 MB.');const text=await f.text(),now=new Date().toISOString(),n={id:'note-'+uid(),title:f.name.replace(/\.txt$/i,''),text,createdAt:now,updatedAt:now};if(persistNotebook({...notebook,notes:[n,...notebook.notes]})){renderNotes();schedule();status('Nota añadida sin sustituir la nota activa.'+(token?' Pendiente de Drive.':' Guardada localmente.'));}}catch(err){status(err.message);}e.target.value='';};
for(const id of ['title','editor','notes','note-title'])el(id).addEventListener('input',schedule);
document.addEventListener('click',e=>{if(e.target.closest('#notes-save,#notes-clear,#note-cards,#apply,#undo,#example,#clear'))setTimeout(schedule,0);});
el('import').addEventListener('change',()=>setTimeout(schedule,0));window.addEventListener('online',()=>{if(token)sync();});
window.addEventListener('beforeunload',e=>{if(token&&(busy||fingerprint(snapshot())!==lastSaved)){e.preventDefault();e.returnValue='';}});
// Public pure functions used by the offline regression suite.
window.AtrilDrive={merge,valid,snapshot};
})();
